In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
!unzip "/gdrive/MyDrive/file/inpaintings.zip" -d "/gdrive/MyDrive/file"

Streaming output truncated to the last 5000 lines.
  inflating: /gdrive/MyDrive/file/inpaintings/4662.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4665.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4666.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4667.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4669.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/467.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4670.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4671.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4673.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4674.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4675.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4678.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4679.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/468.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4680.jpg  
  inflating: /gdrive/MyDrive/file/inpaintings/4681.jpg  
  inflating: /gdrive/MyDrive/file/inpai

In [2]:
import pandas as pd
import numpy as np

In [46]:
df=pd.read_csv("/gdrive/MyDrive/file/final/semevaltest.csv")

In [59]:
df2=pd.read_csv("/gdrive/MyDrive/file/final/semevalnpy.csv")

In [61]:
file_name=df2["file_name"].to_numpy()

In [62]:
file_name.sort()

In [63]:
file_name

array(['1000.jpg', '10000.jpg', '10006.jpg', ..., '9996.jpg', '9997.jpg',
       '9998.jpg'], dtype=object)

In [48]:
images=df["file_name"].to_numpy()

In [49]:
!pip install transformers
from PIL import Image
from transformers import AutoProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = AutoProcessor.from_pretrained("openai/clip-vit-base-patch32")

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [50]:
folder="//gdrive/MyDrive/file/test/testinpainting/"

In [51]:

image = Image.open(folder+"15001.jpg")

inputs = processor(images=image, return_tensors="pt",truncation=True)

image_features = model.get_image_features(**inputs).detach().numpy()

In [ ]:
image_features.shape

(1, 512)

In [ ]:
for i in range(1,len(images)):
  image = Image.open(folder+images[i])
  inputs = processor(images=image, return_tensors="pt")
  features = model.get_image_features(**inputs).detach().numpy()
  image_features=np.append(image_features,features,axis=0)
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [ ]:
image_features.shape

(999, 512)

In [ ]:
np.save("/gdrive/MyDrive/file/textencodings/clipmodeltestenc",image_features)

In [66]:
text=df2["Text Transcription"].to_numpy()

In [67]:
text.shape

(9984,)

In [6]:
from transformers import AutoTokenizer, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")



ModuleNotFoundError: ignored

In [68]:
from transformers import AutoTokenizer, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

inputs = tokenizer(text[0], padding=True, return_tensors="pt",truncation=True)
text_features = model.get_text_features(**inputs).detach().numpy()

In [69]:
text_features.shape

(1, 512)

In [70]:
for i in range(1,len(text)):
  inputs = tokenizer(text[i], padding=True, return_tensors="pt",truncation=True)
  text_features=np.append(text_features,model.get_text_features(**inputs).detach().numpy(),axis=0)
  print(i)

Streaming output truncated to the last 5000 lines.
4984
4985
4986
4987
4988
4989
4990
4991
4992
4993
4994
4995
4996
4997
4998
4999
5000
5001
5002
5003
5004
5005
5006
5007
5008
5009
5010
5011
5012
5013
5014
5015
5016
5017
5018
5019
5020
5021
5022
5023
5024
5025
5026
5027
5028
5029
5030
5031
5032
5033
5034
5035
5036
5037
5038
5039
5040
5041
5042
5043
5044
5045
5046
5047
5048
5049
5050
5051
5052
5053
5054
5055
5056
5057
5058
5059
5060
5061
5062
5063
5064
5065
5066
5067
5068
5069
5070
5071
5072
5073
5074
5075
5076
5077
5078
5079
5080
5081
5082
5083
5084
5085
5086
5087
5088
5089
5090
5091
5092
5093
5094
5095
5096
5097
5098
5099
5100
5101
5102
5103
5104
5105
5106
5107
5108
5109
5110
5111
5112
5113
5114
5115
5116
5117
5118
5119
5120
5121
5122
5123
5124
5125
5126
5127
5128
5129
5130
5131
5132
5133
5134
5135
5136
5137
5138
5139
5140
5141
5142
5143
5144
5145
5146
5147
5148
5149
5150
5151
5152
5153
5154
5155
5156
5157
5158
5159
5160
5161
5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173

In [71]:
text_features.shape

(9984, 512)

In [72]:
np.save("/gdrive/MyDrive/file/textencodings/cliptrainingenc",text_features)

In [19]:
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")



In [88]:
testingfile=df["file_name"].to_numpy()

In [89]:
testingtext=df["Text Transcription"].to_numpy()

In [90]:
len(testingfile)

1000

In [91]:
len(testingtext)

1000

In [92]:
folder="/gdrive/MyDrive/file/test/testinpainting/"

In [93]:
image = Image.open(folder+testingfile[0])
inputs = processor(text=testingtext[0], images=image, return_tensors="pt", padding=True,truncation=True)
outputs = model(**inputs)
img_embed=outputs["image_embeds"].detach().numpy()
text_embed=outputs["text_embeds"].detach().numpy()
logits_per_image = outputs.logits_per_image.detach().numpy()


In [94]:
for i in range(1,len(testingfile)):
  image = Image.open(folder+testingfile[i])
  inputs = processor(text=testingtext[i], images=image, return_tensors="pt", padding=True,truncation=True)
  outputs = model(**inputs)
  img=outputs["image_embeds"].detach().numpy()
  img_embed=np.append(img_embed,img,axis=0)
  txt=outputs["text_embeds"].detach().numpy()
  text_embed=np.append(text_embed,txt,axis=0)
  log= outputs.logits_per_image.detach().numpy()
  logits_per_image=np.append(logits_per_image,log,axis=0)
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [95]:
text_embed.shape,img_embed.shape,logits_per_image.shape

((1000, 512), (1000, 512), (1000, 1))

In [96]:
np.save("/gdrive/MyDrive/file/textencodings/testingtext_embedsclip",text_embed)
np.save("/gdrive/MyDrive/file/imageencodings/testingimage_embedsclip",img_embed)
np.save("/gdrive/MyDrive/file/textencodings/testinglogits_per_imageclip",logits_per_image)

In [44]:
from transformers import AutoTokenizer, CLIPModel

model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

inputs = tokenizer(text[0], padding=True, return_tensors="pt",truncation=True)
text_features = model.get_text_features(**inputs)

In [45]:
text_features==text1

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, F

In [38]:
from PIL import Image
import requests
from transformers import AutoProcessor, CLIPModel
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = AutoProcessor.from_pretrained("openai/clip-vit-base-patch32")
image = Image.open("/gdrive/MyDrive/file/test/testinpainting/15001.jpg")
inputs = processor(images=image, return_tensors="pt")
image_features = model.get_image_features(**inputs)

In [26]:
logits_per_text=outputs.logits_per_text

In [27]:
logits_per_text

tensor([[24.5701],
        [19.3049]], grad_fn=<MulBackward0>)

In [28]:
logits_per_image

tensor([[24.5701, 19.3049]], grad_fn=<TBackward0>)

In [25]:
type(outputs)

transformers.models.clip.modeling_clip.CLIPOutput